version: '3'
services:
  ui:
    stdin_open: true
    build:
      context: ./test-api-calls
    volumes:
      - /app/node_modules
      - ./test-api-calls:/app
    ports:
      - "3000:3000"
  api:
    build:
      context: ./fast-api
    volumes:
      - ./fast-api:/app
    ports:
      - "8000:8000"  
