version: '3'
services:
  nginx:
    depends_on:
      - api
      - ui
    restart: always
    build:
      context: ./nginx
    ports:
      - "3001:80"
  ui:
    stdin_open: true
    build:
      context: ./test-api-calls
    volumes:
      - /app/node_modules
      - ./test-api-calls:/app
  api:
    build:
      context: ./fast-api
    volumes:
      - ./fast-api:/app
