name: Deploy React app to GKE

on:
  workflow_run:
    workflows: Frontend unit tests
    branches: [main]
    types: completed

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: kube-cluster
  GKE_ZONE: us-central1-c
  SHA: ${ GITHUB_SHA:10 }

jobs:
  publish-to-hub:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Publish to dockerhub
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_SHA:10})
    - name: Running deploy script
      run: |-
        docker build -t manosk/multi-ui-k8s:latest -t manosk/multi-ui-k8s:${{steps.vars.outputs.tag}} -f ./test-api-calls/Dockerfile ./test-api-calls
        docker build -t manosk/multi-api-k8s:latest -t manosk/multi-api-k8s:${{steps.vars.outputs.tag}} -f ./fast-api/Dockerfile ./fast-api
        docker push manosk/multi-ui-k8s:latest
        docker push manosk/multi-api-k8s:latest
        docker push manosk/multi-ui-k8s:${{steps.vars.outputs.tag}}
        docker push manosk/multi-api-k8s:${{steps.vars.outputs.tag}}
  setup-and-deploy:
    needs: publish-to-hub
    name: Setup and Deploy to k8s
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Get the GKE credentials so we can deploy to the cluster
    - run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
    # Deploy sample image to the GKE cluster
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_SHA:10})
    - name: Deploy
      run: |-
        kubectl apply -f k8s/
        kubectl set image deployments/api server=manosk/multi-api-k8s:${{steps.vars.outputs.tag}}
        kubectl set image deployments/ui client=manosk/multi-ui-k8s:${{steps.vars.outputs.tag}}
        kubectl get services -o wide
